### ISSUE TITLE
Registering Functionality

### ISSUE THREAD

**Issue by t-haich** [Angblah/The-Comparator#1]
As a user, I want the ability to register so that I can access account-related storage such as saved comparisons or comparison templates

**Comment by alexyuisingwu** [comment]
functionality currently in, but error messages/registration confirmation are fairly ugly. Also, no confirmation email is being sent yet (should that be another issue, or part of this one?)

**Comment by honeychawla** [comment]
I'm going to try to handle error messages/confirmation for registration

**Comment by honeychawla** [comment]
Error messages handled. Still need the case for when both username and email are already taken

**Comment by alexyuisingwu** [comment]
Error for when both username and email handled (though a little ugly, as both messages are stacked on each other instead of combined).

**Comment by t-haich** [comment]
Need to fix situation where both username and email are empty

**Comment by honeychawla** [comment]
Handled null fields when trying to register. Right now they show up as separate messages. They can be combined if they need to be.
