### ISSUE TITLE
Database Template Saving

### ISSUE THREAD

**Issue by t-haich** [Angblah/The-Comparator#10]
As a registered user, I want to be able to save templates that I can reuse for similar comparisons in the future

**Comment by alexyuisingwu** [comment]
Partially done (save as template implemented in 

def save_comparison_as_template(comparison_id, template_name)

or the stored function:

save_comparison_as_template (_comparison_id int, _template_name varchar)

**Comment by alexyuisingwu** [comment]
Top loading washer, laptop, camera templates put into admin templates. Template attributes can be added through stored function (deletion is just deleting by key through attribute id). Templates can get viewed through get_template(template_id).

**Comment by alexyuisingwu** [comment]
template copying function written (so that when users edit default templates, new template is made first and attributes can be added to this new template).

copy_template (_template_id int, _account_id int) returns int
