### ISSUE TITLE
Make more default templates

### ISSUE THREAD

**Issue by Angblah** [Angblah/The-Comparator#103]
Make more default template options.
Possibilities include:

- [ ] Credit Cards

- [ ] Banks

- [ ] Other Washers

- [ ] Dishwashers

- [x] Phones

- [x] Cars

- [ ] Vacuums

- [ ] Fridge

- [x] Kitchen Sink

**Comment by alexyuisingwu** [comment]
Phone, Car, Sink, Fridge templates and comparisons in.
