### ISSUE TITLE
Images in Database Research

### ISSUE THREAD

**Issue by honeychawla** [Angblah/The-Comparator#31]
How are we going to save images in the database?

**Comment by honeychawla** [comment]
We have settled on using Cloudinary.

**Comment by alexyuisingwu** [comment]
cloudinary example code in heroku (thecomparator.herokuapp.com/image_upload_example). Conversion to jquery + integration with workspace pending.

**Comment by alexyuisingwu** [comment]
basic user avatar upload in (though styling still needs to be fixed, and it would be nice to keep restrict total user image storage, warn users of avatar display size, tag images with user info to allow easier deletion of images, and allow avatars to be updated without page refresh (ajax?)

**Comment by alexyuisingwu** [comment]
images stored in folder structure to facilitate easy delete of user images, file size limit enforced on avatar upload (10 mebibytes per user as of now), appropriate error message on file size excess added.
