### ISSUE TITLE
Recover Lost Password

### ISSUE THREAD

**Issue by t-haich** [Angblah/The-Comparator#4]
As a registered user, I want to be able to recover my password if I forget it so I can still access my account

**Comment by honeychawla** [comment]
Invalid username and email have been handled!

**Comment by alexyuisingwu** [comment]
basic functionality (email for link to reset password) done. Still lacking error message for invalid user input, actually secret keys/not very polished though.

**Comment by honeychawla** [comment]
Error message for invalid user input has been handled, as well as a success message

**Comment by alexyuisingwu** [comment]
Error message for incorrect reset link and success message for changing password handled. Login modal links still lead to incorrect places (merely appends "profile"/"forgotPassword" to end of /reset/ url. Password constraint (>0 characters) needs to be displayed for user in same format as constraints for other forms.

**Comment by honeychawla** [comment]
Login modal /profile link has been fixed
