### ISSUE TITLE
Route to Workspace from Dashboard

### ISSUE THREAD

**Issue by t-haich** [Angblah/The-Comparator#45]

**Comment by alexyuisingwu** [comment]
Done for recent comparisons and comparisons in general (though ui might change)

**Comment by honeychawla** [comment]
We still need to use the comparisonId in functions, since right now it's hardcoded.

**Comment by honeychawla** [comment]
Done! :D Using state.id and state.info.name as arguments to functions for the database calls. So now, nothing is hardcoded meaning we can use other comparisons, not just the washer one.
