### ISSUE TITLE
Basic Templates in Database

### ISSUE THREAD

**Issue by t-haich** [Angblah/The-Comparator#6]
As a user, I want to quickly create a comparison by choosing from templates so that I may quickly and easily start my search

**Comment by honeychawla** [comment]
This requires updating database_utils so that calling populate_database creates all the default templates.

**Comment by alexyuisingwu** [comment]
Top loading washer, laptop, camera templates put into admin templates. Template attributes can be added through stored function (deletion is just deleting by key through attribute id). Templates can get viewed through get_template(template_id).

NOTE: all basic/example templates will be attached to admin.
