### ISSUE TITLE
Select Template UI and Routing

### ISSUE THREAD

**Issue by t-haich** [Angblah/The-Comparator#8]
As a user, I want to quickly create a comparison by choosing from templates so that I may quickly and easily start my search

**Comment by honeychawla** [comment]
Selecting "New Comparison" on a user's dashboard opens the Select a Template modal. The user can choose a default template to start their comparison with, or start one from scratch.

Issues: We save everything to the same comparison id, lol. So when we create a new template, need to assign it a new compId.

**Comment by alexyuisingwu** [comment]
Done (though admin templates should be cleaned up).

**Comment by alexyuisingwu** [comment]
NOTE: routing is done, not template viewing+editing
